### ISSUE TITLE
Something's wrong on grad_check.. Errors for every activation function except ReLU

### ISSUE THREAD

**Issue by saranpan** [wallik2/dipple#1]
Gradcheck reports that the difference between approx gradient and true gradient are significantly large (1 digit error ) for every activation except ReLU

**Comment by wallik2** [comment]
1 . S

**Comment by saranpan** [comment]
Suspected :

**Comment by saranpan** [comment]
Suspected :

1. binary_accuracy
2. model.predict
3. L_backward

**Comment by saranpan** [comment]
Fixed 👍🏻 

The problem was found in this function:

Before:
def gradient_check_n(parameters, gradients, X, Y , epsilon = 1e-7): 

After : 
def gradient_check_n(parameters, gradients, X, Y,  **activation_function**, **last_activation_function** , epsilon = 1e-7): 

Since gradient_check_n depends on L_model_forward, and the default activation_function and last activation_function is 'relu','sigmoid', so this function approximates with the wrong assumption with the default activation function
